### ISSUE TITLE
Failed to execute [org.elasticsearch.action.search.SearchRequest@66882f22] lastShard [true]

### ISSUE THREAD

**Issue by yrmallu** [oneops/display#188]
[2017-05-24 16:42:38,952][DEBUG][action.search.type       ] [Ajax] [cms-2017-w18][4], node[Esi_VQ09S9C6Aw7n6bjsyg], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@66882f22] lastShard [true]
org.elasticsearch.search.SearchParseException: [cms-2017-w18][4]: query[*:*],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"must":[]}},"aggs":{"group_by_ns":{"terms":{"field":"nsPath.keyword","size":9999},"aggs":{"latest":{"top_hits":{"sort":[{"created":{"order":"desc"}}],"size":1}}}}}}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:747)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:572)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:544)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:306)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.search.SearchParseException: [cms-2017-w18][4]: query[*:*],from[0],size[3]: Parse Failure [No mapping found for [created] in order to sort on]
        at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:214)
        at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:188)
        at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:86)
        at org.elasticsearch.search.aggregations.metrics.tophits.TopHitsParser.parse(TopHitsParser.java:75)
        at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:148)
        at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:138)
        at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:78)
        at org.elasticsearch.search.aggregations.AggregationParseElement.parse(AggregationParseElement.java:60)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:731)
        ... 9 more

**Comment by mosabua** [comment]
Issue tracking is migrated to Walmart JIRA and https://github.com/oneops/oneops.
